jobs:
  build:
    docker:
      - image: circleci/node:8.9.4

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: npm preparation
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: 
          name: Install
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: Lint
          command: npm run lint
      - run: 
          name: Unit Tests
          command: npm test

version: 2.1

version: 2
jobs:
  local_test:
    ...
  fullstack_test:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: Install curl
          command: apt-get update && apt-get install -y curl
      - run:
          name: "Trigger full-stack test"
          command: "curl -u ${CIRCLE_API_KEY}: -d build_parameters[CIRCLE_JOB]=start_workflows https://circleci.com/api/v1.1/project/github/<company>/testing/tree/master"
workflows:
  version: 2
  local_and_fullstack_tests:
    jobs:
      - local_test
      - fullstack_test:
          filters:
            branches:
              only:
                - master